# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
        ('proxies.txt', '.'),
        ('model', 'model'),
        ('fazendoLogin.py', '.'),
        ('ListandoRotas2.py', '.'),
        ('enviarEmail.py', '.'),
        ('pegarValorObservacao.py', '.'),
        ('validarLetraProduto.py', '.'),
        ('icone.ico', '.'),
    ],
    hiddenimports=[
        'PySimpleGUI',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        'tkinter.colorchooser',
        'tkinter.commondialog',
        'tkinter.constants',
        'tkinter.dnd',
        'tkinter.font',
        'tkinter.scrolledtext',
        'tkinter.tix',
        'tkinter.turtle',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support',
        'selenium.common.exceptions',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.common.action_chains',
        'selenium.webdriver.support.wait',
        'pandas',
        'numpy',
        'unidecode',
        'bs4',
        'beautifulsoup4',
        'requests',
        'lxml',
        'email.mime.multipart',
        'email.mime.text',
        'email.mime.image',
        'smtplib',
        'ssl',
        'threading',
        'datetime',
        'time',
        'logging',
        'sys',
        'os',
        'random',
        'urllib.parse',
        'pathlib',
        'shutil',
        'subprocess',
        'traceback',
        'zipfile',
        'json',
        'webdriver_manager',
        'webdriver_manager.chrome',
        'mysql.connector',
        'pymysql',
        'sqlite3',
        'sqlalchemy',
        'psycopg2',
        'cx_Oracle',
        'pkg_resources',
        'setuptools',
        'distutils',
        'encodings',
        'codecs',
        'locale',
        'gettext',
        'weakref',
        'collections',
        'itertools',
        'functools',
        'operator',
        'types',
        'builtins',
        'importlib',
        'importlib.machinery',
        'importlib.util',
        'importlib.abc',
        '_tkinter',
        'tkinter._tkinter',
        'tkinter.tkinter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'PIL',
        'cv2',
        'torch',
        'tensorflow',
        'jupyter',
        'notebook',
        'IPython',
        'pytest',
        'unittest',
        'doctest',
        'test',
        'tests',
        'testing',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='madeforte',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icone.ico'
)
